#4 Create remove user from activity diagram sequence
orion-services/Activity pull request #12
Opened 2021-07-28 02:03 UTC by nikolasFreitas

# Create remove user from activity diagram sequence

### Closes #4 

----
Diagram result:

![image](https://user-images.githubusercontent.com/13020492/127251886-820f0598-9689-497c-a0c0-9a9c472d8248.png)

2021-07-28 03:20 UTC, rodrigoprestesmachado commented
We need to add a note (maybe near of DB), we can remove the user of a activity/group, but, we **can't** remove the history of a user

2021-08-01 13:39 UTC, GiovaniBoff requested changes

2021-08-01 13:39 UTC, GiovaniBoff commented on docs/sequence/remove-user-from-activity.wsd
> +    hisotry of the user in
Adjust this note, history is written wrong

2021-08-03 01:39 UTC, evandroLutz submitted a review, later dismissed
could replace "remove me" with "remove user request"

2021-08-06 00:51 UTC, nikolasFreitas commented
> remove user

I think the "request" is not necessary, but I will change to "remove user"

2021-08-06 01:54 UTC, GiovaniBoff approved these changes

2021-08-06 01:54 UTC, merged